"""
This type stub file was generated by pyright.
"""

from datetime import datetime
from typing import Any

from pydantic import BaseModel, field_validator

"""
This type stub file was generated by pyright.
"""

class Media(BaseModel):
    url: str
    title: str
    type: str
    imdb: str | None = ...
    status: str
    last_updated: datetime | None = ...
    info_hash: str | None = ...
    size: str | None = ...
    seeders: int | None = ...
    leechers: int | None = ...
    @field_validator("type")
    @classmethod
    def type_is_movie_or_tv(cls: Any, v: Any): ...
    @field_validator("imdb", mode="before")
    @classmethod
    def fix_imdb_id(cls: Any, v: Any): ...
